package main

type DataPacket struct {
	Timestamp uint32
	Mode uint32
	PressureThrusterTank float32
	PressureBrakingTank float32
	PressureBrakingExtend float32
	PressureBrakingCompress float32
	TemperatureThrusterLeftTank float32
	TemperatureThrusterRightTank float32
	TemperatureThrusterNozzle float32
	TemperatureBattery float32
	TemperatureBrakingTank float32
	TemperatureBrakingExtend float32
	TemperatureBrakingCompress float32
	Speed float32
	Distance float32
	Vibration1 float32
	Vibration2 float32
	Vibration3 float32
	Vibration4 float32
	ActuationThruster bool
	ActuationRelieveValve bool
	ActuationSafetyValve bool
	ActuationBrakingValve bool
	CurrentThrusterLeftValve float32
	CurrentThrusterRightValve float32
	CurrentThrusterRelieveValve float32
	CurrentBrakingValve float32
	CurrentNAP float32
	CurrentBattery float32
	VoltageThrusterLeftValve float32
	VoltageThrusterRightValve float32
	VoltageThrusterRelieveValve float32
	VoltageBrakingValve float32
	VoltageNAP float32
	VoltageBattery float32
	Orientationx float32
	Orientationy float32
	Orientationz float32
	Accelerationx float32
	Accelerationy float32
	Accelerationz float32
	ImuStatus uint32
	BrakeStatus uint32
	PropulsionStatus uint32
	EmergencyBrake bool
}
